### ISSUE TITLE
KeePassX 0.4.4 - Start Minimized Doesn't Appear 

### ISSUE THREAD

**Issue by ghost** [bbidulock/blackboxwm#17]
In 0.72.6 I noticed when you have KeePassX 0.4.4 settings ```start minimized``` checked, when you start it, then middle click and bring up the workspaces and iconified menu, KeePassX does not appear in it.

**Comment by bbidulock** [comment]
Find the window with

    xwininfo -root -all

and then

    xprop -id 0x0000000 WM_HINTS WM_STATE

where 0x0000000 need to be replaced by the window id you found.  The "initial state" should be "Iconic" and the "window state" should also be "Iconic".

Then also check

    xprop -id 0x0000000 _NET_WM_STATE

It had better not contain _NET_WM_STATE_SKIP_TASKBAR, otherwise it will not appear even in the iconified window list.

If that is not the problem, post the results of the above tests.
