### ISSUE TITLE
Can't launch using gsettings

### ISSUE THREAD

**Issue by micwoj92** [bbidulock/blackboxwm#36]
Hello, I am using blackbox 0.76-1 from Arch Linux community repo. I am using MATE desktop and I tried to change to this WM using [instructions from the wiki](https://wiki.archlinux.org/index.php/MATE#Use_a_different_window_manager) 

Using gsettings it did not work, but I could just add blackbox to autostart and I am using it right now.

I checked with different wm's (metacity and ukwm) it worked as expected so it is not gsettings issue.

**Comment by bbidulock** [comment]
Well, yes, it is the way that gsettings invokes the window manager.  It works with Metacity because Metacity is gnome2's original window manager.  It works with ukwm because ukwm has the same command line options as Metacity.  Also, both support X11R6 session management: blackbox does not.  See ``man metacity``, ``man ukwm`` and ``man blackbox`` to see what I mean.

**Comment by micwoj92** [comment]
In todo there is item called "session support via the X session management protocol". Is this the same thing you are talking about?
